server:
  port: 8080
spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/my_demo?characterEncoding=UTF-8

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    driver-class-name: com.mysql.jdbc.Driver

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: true #pageSize=0